name:  Go
on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:

  Analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Analyze 🔍
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

  Run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Test 🔧
        run: |
          make ci-test
          make stop-docker-test

      - name: Upload coverage 📤
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          fail_ci_if_error: true
